name: Greetings for New Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the user's first contribution
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome, @${{ github.actor }}! Thanks for creating the first issue in this repository. We will review it soon!"
          pr-message: "Welcome, @${{ github.actor }}! Thanks for your first pull request in this repository. We will definitely check it out!"
